export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const FETCH_ORDER_INIT = 'FETCH_ORDER_INIT';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_DATA_RECIEVED = 'USER_DATA_RECIEVED';
export const RECIEVE_USER_DATA = 'RECIEVE_USER_DATA';

export const CHANGE_USER_INPUT = 'CHANGE_USER_INPUT';
